### ISSUE TITLE
CompositeKind not defined

### ISSUE THREAD

**Issue by astrieanna** [pao/QuickCheck.jl#1]
I'm not quite sure what the type `CompositeKind` was, so I'm not sure how to fix this:

```
ERROR: CompositeKind not defined
 in generator at /home/leah/.julia/QuickCheck/src/QuickCheck.jl:80
 in anonymous at /home/leah/.julia/QuickCheck/src/QuickCheck.jl:21
 in check_property at /home/leah/.julia/QuickCheck/src/QuickCheck.jl:53
 in quantproperty at /home/leah/.julia/QuickCheck/src/QuickCheck.jl:38
 in property at /home/leah/.julia/QuickCheck/src/QuickCheck.jl:22
 in property at /home/leah/.julia/QuickCheck/src/QuickCheck.jl:24
```

It comes from this function:

```
# Generator for composite types
function generator{C}(::Type{C}, size)
    if !isa(C, CompositeKind)
        error("No generator defined for type $C.")
    end
    C([generator(T, size) for T in C.types]...)
end
```

Probably irrelevant: 
- I'm on the development version of Julia, on Linux.
- I was trying to run `property((f::Function -> f(4) == 6),[Function])`, without expecting it to actually be able to generate functions.

**Comment by pao** [comment]
`CompositeKind` was the old name for the type of composite types. That was scrapped some time ago. This check might need to be for the existence of the `.types` field now, since there's no type-level way to distinguish things with fields.

I'm not sure how you're expecting this to work without generating functions--the test isn't abstract manipulation, it's trying to show evidence for the validity of a universally-quantified expression. The property `property((f::Function -> f(4) == 6),[Function])` is saying "For all Functions, `f(4) == 6`", and attempting to show that by plugging in randomly generated Functions (which QuickCheck doesn't know how to do.)

**Comment by astrieanna** [comment]
I meant that I wasn't expecting it to work because it doesn't know how to generate Functions.

Ok. It looks like checking for `C.types == ()` would work:

```
julia> Int.types
()

julia> Rational.types
(T<:Integer,T<:Integer)

julia> Array{Int,1}.types
()

julia> String.types
()

julia> ASCIIString.types
(Array{Uint8,1},)
```
